spring:
  application:
    name: mc
  redis:
#    host: 127.0.0.1
#    port: 6379
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}

    jedis:
      pool:
        enabled: true

server:
  port: 8080
  servlet:
    context-path: /
logging:
  level:
    root: info

sms:
  host: ${MOKE_SERVER_HOST:mock-sms-server}
  port: ${MOKE_SERVER_PORT:8080}